- name: Убедиться, что директория /etc/nginx существует
  file:
    path: /etc/nginx
    state: directory
    mode: "0755"

- name: Скопировать конфиг nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Перезапустить nginx